name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Run tests
        run: ./gradlew test

      - name: List generated files in CI
        if: always() # Ejecutar siempre para ver qué pasó
        run: |
          echo "Listing contents of build/test-results/test/ directory in CI:"
          ls -R build/test-results/test || echo "CI: Directory build/test-results/test/ not found or empty."
          echo "-----------------------------------------------------"
          echo "Specifically listing XML files in build/test-results/test/ in CI:"
          find build/test-results/test -name "*.xml" -type f -print || echo "CI: No XML files found in build/test-results/test/"
          echo "-----------------------------------------------------"
          echo "Listing ALL XML files under build/test-results/ in CI (recursive):"
          find build/test-results -name "*.xml" -type f -print || echo "CI: No XML files found anywhere under build/test-results/"

      - name: Generate test report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Test Results (JUnit)
          path: build/test-results/test/*.xml
          reporter: java-junit